/* tslint:disable */
/* eslint-disable */
/**
 * User Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsersIdDelete200Response
 */
export interface UsersIdDelete200Response {
    /**
     * 
     * @type {string}
     * @memberof UsersIdDelete200Response
     */
    status?: string;
}

/**
 * Check if a given object implements the UsersIdDelete200Response interface.
 */
export function instanceOfUsersIdDelete200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UsersIdDelete200ResponseFromJSON(json: any): UsersIdDelete200Response {
    return UsersIdDelete200ResponseFromJSONTyped(json, false);
}

export function UsersIdDelete200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersIdDelete200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': !exists(json, 'status') ? undefined : json['status'],
    };
}

export function UsersIdDelete200ResponseToJSON(value?: UsersIdDelete200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
    };
}

